services:
  postgres:
    image: postgres:16-alpine
    container_name: finbank-postgres
    environment:
      POSTGRES_DB: finbank
      POSTGRES_USER: finbank
      POSTGRES_PASSWORD: finbank
    ports:
      - "5434:5432"
    volumes:
      - finbank_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U finbank -d finbank"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  finbank_pgdata:
